### PR TITLE
Changes for upstream

### PR DESCRIPTION
**Pull request by ukos-git**
Integration of various changes from forked project back to upstream

As the upstream project probably is the more popular it should also profit from changes made in forked projects.
The updated Readme.md contains the changes.

### CODE REVIEW

**Comment by ukos-git** [comment]
I can not imaging where the confilict comes from. I cannot resolve it either because i have no write access to the repo.

**Comment by petervannes** [comment]
The conflict on processmail.sh is odd indeed. I do currently not have the time to review the changes but will try to review in one or two weeks.

**Comment by ukos-git** [comment]
I resolved the conflict. It was due to the inserted if statement by @davearias in b3a650e7.
Didn't realize that I can actually rebase the branch when the MR was already started.

Take your time for the MR. I just started with your project a few days ago.

**Comment by ukos-git** [comment]
Why did you close the MR without merging?
I saw, you made changes to master, yourself. I could imagine, there were some conflicts? Was this the reason to close the MR?

**Comment by petervannes** [comment]
Hi Matthias,

The installation and configuration scripts were based on Wheezy. When i had to reconfigure my Pi due to a crash using Jessie i had to make quite some modifications to get it up and running again. So merging issues would arise obviously. Main reason why i did close the the MR is because your modifications are changing and adding functions which i initially explicitly did not build in. So to my opinion your modifications and additions should continue in another branch / fork. I did write this application for one reason (as explained in my blog article) and made it available to others for re-use, adaption etc. So please continue making you own improvements as davearias did.

Cheers,
Peter

**Comment by ukos-git** [comment]
> adding functions
you probably meant adding functionality.

I can understand you but the changes were not so dramatic as you might think.
It was mostly bugfix, cleanup and the use of built-in functionality (rpi-update, raspi-config etc) instead of hard-coding system changes. 

The changes from the MR were already compatible with debian 8. Please also note that debian 9 is 2 weeks away as of now. Probably the removing dist-upgrade from your script would be a good idea.

**Pull request closed without merging**
